package com.packagefactory.factory.core.constants;

public enum SuccessStatus {
    ENTRY_CREATED,
    ENTRY_UPDATED,
    ENTRY_DELETED,
    ENTRY_FOUND,
    REGION_CREATED,
    REGION_FOUND,
    REGION_UPDATED,
    REGION_DELETED,
    PRICE_CATEGORY_CREATED,
    PRICE_CATEGORY_FOUND,
    PRICE_CATEGORY_UPDATED,
    PRICE_CATEGORY_DELETED,
    VENDOR_CREATED,
    VENDOR_FOUND,
    VENDOR_UPDATED,
    VENDOR_DELETED,
    CUSTOMER_CREATED,
    CUSTOMER_FOUND,
    CUSTOMER_UPDATED,
    CUSTOMER_DELETED,
    SUPPLIER_CREATED,
    SUPPLIER_FOUND,
    SUPPLIER_UPDATED,
    SUPPLIER_DELETED
}
